[build-system]
requires = ["setuptools", "setuptools-scm","scikit-build", "cmake"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ICARUS*"]
exclude = ["Data*", "tests*"]

[project]
name = "ICARUS"
authors = [
    {name = "Tryfonas Themas", email = "tryfonthem@gmail.com"},
]
description = "ICARUS AIRPLANE DESIGN"
readme = "README.md"
requires-python = ">=3"
dependencies = [
    "pip",
    "airfoils",
    "jsonpickle",
    "matplotlib",
    "numpy",
    "pandas",
    "ipykernel",
    "ipython",
    "tabulate",
    #"xfoil @git+https://github.com/trifwn/xfoil-python-windows.git",
    "xfoil @git+https://github.com/DARcorporation/xfoil-python.git",
]
dynamic = ["version"]

[mypy]
plugins = "numpy.typing.mypy_plugin"
